config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :plants  do
    resources :bookings, only: [:index, :show, :new, :create, :delete]
  end
  resources :users, except: [:index, :new, :create]

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :plant

  validates :user, uniqueness: { scope: :plant }
  validates :time, presence: true, numericality: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :bookings

  validates :name, :family, presence: true
  validates :price_per_day, :size_cm, presence: true, numericality: true
  validates :description, :water, :sun, :ext_int, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :plants
  has_many :bookings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  protected
    def after_sign_in_path_for(resource)
      plants_path
    end

    def after_sign_out_path_for(resource)
      plants_path
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: [:show, :new, :destroy]

  def index
    @bookings = current_user.bookings
  end

  def show
  end

  def new
    @plant = Plant.find(params[:plant_id])
    @booking = Booking.new
  end

  def create
    @plant = Plant.find(params[:plant_id])
    @booking = Booking.new(booking_params)
    @booking.plant = @plant
    @booking.save
    @booking.user = current_user
    if @booking.save
      redirect_to plant_bookings_path
    else
      redirect_to plants_path(@plant)
    end
  end

  def destroy
    @booking.destroy
    redirect_to
  end

  private

  def booking_params
    params.require(:booking).permit(:time, :price, :user_id, :plant_id)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plants, only: %i[show edit update destroy]

  def index
    @plants = Plant.all
    @plant = Plant.new
  end

  def show

    @booking = Booking.new
  end

  def new
    @plant = Plant.new
  end

  def edit
  end

  def update
    @plant.update(plants_params)
    redirect_to plant_path(@plant)
  end

  def create
    @plant = Plant.new(plants_params)
    @plant.user = current_user
    if @plant.save!
      redirect_to plant_path(@plant)
    else
      render :new
    end
  end

  def destroy
    @plant.destroy
    redirect_to plant_path
  end

  private

  def set_plants
    @plant = Plant.find(params[:id])
  end

  def plants_params
    params.require(:plant).permit(:name, :family, :description, :water, :sun, :ext_int, :size_cm, :price_per_day, :flowers, :photo, :booking_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_users, only: [:show, :edit]

  def show
    # set_users
  end

  def edit
    # set_users
  end

  # def destroy
  #   @user.destroy
  #   redirect_to plants_path(@plant)
  # end

  private

  def set_users
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h3> Mes réservations </h3>
  <% @bookings.each do |booking| %>
    <div class="card-product">
    <%= cl_image_tag "#{booking.plant.photo}" %>
      <div class="card-product-infos">
        <h2><%= booking.plant.name%></h2>
        <p><%= booking.plant.family%></p>
        <p><strong><%= booking.time * booking.plant.price_per_day %>€</strong></p>
        <%=link_to "Réserver à nouveau", plant_bookings_path, class: 'btn-booking', id:"button-right" %>
      </div>
      <%= link_to " ", plant_path(booking.plant), class: "card-link" %>
    </div>
  <% end %>

app/views/bookings/show.html.erb
<h1> Mes réservations </h1>


  <% @bookings.each do |booking| %>

  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Plant to rent</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>
  <body>
<% if current_page?(root_path) %>

  <div class="wrapper-home">
      <div class="container">
       <%= yield %>

      </div>
    </div>

<%else %>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="wrapper">
      <div class="container">
       <%= yield %>

      </div>
    </div>

    <% end %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-flex">
<div class="home-content">

  <h1 class="title-home">Plant to rent</h1>
  <p class="tagline-home">Location de plantes pour vos évènements</p>

  <div class="home-form">

      <form action="">
        <div class="label-form">

          <input type="text">
        </div>
        <div class="select-form">
          <select name="" id="">
            <option value="">-- Type de plante --</option>
            <option value="dog">plantes grasses</option>
            <option value="cat">plantes vertes</option>
            <option value="cat">plantes fleuries</option>
            <option value="cat">arbustes</option>
            <option value="cat">arbres fruitiers</option>
          </select>
        </div>
        <div class="text-center button-form">

          <%= link_to "Rechercher", plants_path, class: "button" %>
        </div>
      </form>

  </div>

</div>
</div>

app/views/plants/edit.html.erb
<h1>Update plant</h1>
<%= simple_form_for @plant do |f| %>
  <%= f.input :name %>
  <%= f.input :family %>
  <%= f.input :description %>
  <%= f.input :water %>
  <%= f.input :sun  %>
  <%= f.input :ext_int %>
  <%= f.input :size_cm %>
  <%= f.input :price_per_day %>
  <% f.input :created_at  %>
  <% f.input :user_id  %>
  <%= f.input :photo %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/plants/index.html.erb
<div class="cards">
  <% @plants.each do |plant| %>
  <div class="card">
    <div class="card-img" style="background-image: url('<%= cl_image_path plant.photo,  crop: :fill %>')">
    </div>
      <div class="card-txt">
        <p><%= plant.family.capitalize %></p>
          <h3><%= plant.name.capitalize %></h3>
            <div class="price">
              <p><%= plant.price_per_day %>  € <span>/jour</span></p>
            </div>
            <% avatar_style = plant.user.photo.blank? ? "background-image: url('https://res.cloudinary.com/dvvkrrjc4/image/upload/v1550842670/Screen_Shot_2019-02-22_at_14.37.36.png')" : "background-image: url('#{cl_image_path plant.user.photo,  crop: :fill}')" %>
            <div class="card-avatar" style="<%= avatar_style %>">
            </div>
      </div>
        <%= link_to " ", plant_path(plant), class: "card-link" %>
  </div>
  <% end %>
</div>

app/views/plants/new.html.erb
    <div class="form ">

      <h3 class="text-center">Ajouter une plante</h3>

        <%= simple_form_for @plant do |f| %>
        <div class="label-form">
          <%= f.input :name %>
        </div>

        <div class="select-form">
          <%= f.select :family, { 'plantes grasses' => "plantes grasses", 'plantes vertes' => "plantes vertes", 'plantes fleuries' => "plantes fleuries", 'arbustes' => "arbustes", 'arbres fruitiers' => "arbres fruitiers"}, include_blank: false, :label => "Famille", :prompt => "-- Type de plante --" %>
        </div>

        <div class="label-form">
          <%= f.input :description %>
        </div>
        <div class="select-form">
          <%= f.select :water, { 'un peu' => "un peu", 'beaucoup' => "beaucoup", 'passionnément' => "passionnément", 'à la folie' => "à la folie"}, include_blank: false, :label => "Eau", :prompt => "-- Quantité d'eau --" %>
        </div>
        <div class="select-form">
          <%= f.select :sun, { 'un peu' => "un peu", 'beaucoup' => "beaucoup", 'passionnément' => "passionnément", 'à la folie' => "à la folie"}, include_blank: false, :label => "Soleil", :prompt => "-- Ensoleillement --" %>
        </div>
        <div class="select-form">
          <%= f.select :ext_int, { 'intérieur' => "un peu", 'extérieur' => "extérieur"}, include_blank: false, :label => "Emplacement", :prompt => "-- Emplacement --" %>
        </div>
        <div class="label-form">
          <%= f.input :size_cm %>
        </div>
        <div class="label-form">
          <%= f.input :price_per_day %>
        </div>
          <% f.input :created_at  %>
          <div class="label-form">
          <%= f.input :photo %>
          </div>
          <div class="text-center">
          <%= f.button :submit,"Ajouter",  class: 'button' %>

          </div>
        <% end %>
      </div>

</div><!-- end col -->

</div><!-- end row -->

app/views/plants/show.html.erb
<div class="container-show">
  <div class="left">

    <div>
      <%= cl_image_tag "#{@plant.photo}", class:"plant-photo"%>
    </div>

    <div id="backbutton">
      <%=link_to "Retour", plants_path, class: 'button' %>
    </div>

  </div>

  <div class="plant-details">

    <% if current_user == nil %>
      <% elsif @plant.user_id == current_user.id  %>
      <div class="prix-user">
        <p id="prix-modif"><%= @plant.price_per_day%> €</p>
        <p>/ jour</p>
      </div>
      <% end %>

    <div class="namefamily">
      <h2 id="name"><%= @plant.name %></h2>
      <p id="family"><%= @plant.family %></p>
    </div>

    <div class="infos">
      <div class="entretien">

        <div id="water"><p>Eau</p>
          <p class="textcentre"><i class="fas fa-tint padding-icon"></i><%=@plant.water %></p>
        </div>

        <div id="sun"><p>Soleil</p>
          <p class="textcentre"><i class="fas fa-sun padding-icon"></i><%=@plant.sun %></p>
        </div>

      </div>

      <div class="localisation">

        <div id="ext_int"><p>Emplacement</p>
          <p class="textcentre"><i class="fas fa-thermometer-half padding-icon"></i><%=@plant.ext_int%></p>
        </div>

        <div id="size"><p>Taille</p>
          <p class="textcentre"><i class="fas fa-ruler-combined padding-icon"></i><%=@plant.size_cm%> centimètres</p>
        </div>

      </div>

    </div>

    <div class="citation">

      <div id="motproprio">Un petit mot de mon·ma propriétaire...</div>
      <div id="description">"<%= @plant.description %>"</div>

      <% if current_user == nil %>
      <% elsif @plant.user_id == current_user.id  %>
        <div class= "button-edit">
          <%=link_to "Modifier", edit_plant_path, class: 'button' %>
        </div>
      <% end %>

    </div>

  </div>


  <% if current_user == nil || @plant.user_id != current_user.id %>
  <% current_user %>
    <div class="book-and-back">
      <div class="prix">
        <p id="prixeneuros"><%= @plant.price_per_day%> €</p>
        <p>/ jour</p>
      </div>
      <div class="formbooking">
        <p> Je souhaite louer cette plante.
        Elle me sera livrée à l'adresse et au jour de mon choix.</p>
        <div id="form"><%= simple_form_for ([@plant, @booking]) do |f| %>
          <%= f.input :time , label:"Nombre de jours" %>
          <%= f.button :submit ,"Réserver", class: 'button' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <% if current_user == nil %>
  <% elsif @plant.user_id == current_user.id  %>
    <div class="profile">



      <div class="mon-profil">

        <p id="titre-profile">Mon profil</p>

        <div>
          <%= cl_image_tag current_user.photo, id:"user-photo" %>
        </div>

        <div id="user-mail">
          <%= current_user.email %>
        </div>

        <div id="user-adress">
        <%= current_user.address %>
        </div>

      </div>

      <div class= "button-edit-profile">
        <%=link_to "Modifier", edit_plant_path, class: 'button' %>
      </div>

    </div>

  <% end %>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
 <div class="navbar-container">
 <div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to "Plant to rent", plants_path, class: "navbar-wagon-logo"%>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <!-- Links when logged in -->

      <%= link_to "Mes plantes", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Mes réservations", plant_bookings_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.photo.present? %>
            <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown"  %>
          <% else %>
            <i class="fab fa-pagelines avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown"></i>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Mon profil") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Se déconnecter") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Se connecter | S'inscrire"), new_user_session_path, class: "btn-connect navbar-wagon-item navbar-wagon-link " %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>
</div>

app/views/users/show.html.erb
<h3 class="title-user">Mes plantes</h3>
<div class="cards">
  <% @user.plants.each do |plant| %>
  <div class="card">
    <div class="card-img" style="background-image: url('<%= cl_image_path plant.photo,  crop: :fill %>')">
    </div>
      <div class="card-txt">
        <p><%= plant.family.capitalize %></p>
          <h3><%= plant.name.capitalize %></h3>
            <div class="price">
              <p><%= plant.price_per_day %>  € <span>/jour</span></p>
            </div>
      </div>
        <%= link_to " ", plant_path(plant), class: "card-link" %>
  </div>
  <% end %>
  <div class="card empty">
    <div class="add-body">
      <div class="circle-add">
        <h1>+</h1>
      </div>
      <p>ajouter une plante</p>
    </div>
    <%= link_to " ", new_plant_path, class: "card-link" %>
  </div>
</div>